<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNZ2URE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNZ2URE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNZ2URE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNZ2URE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVNZ2URE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VNZ2URE',
    'container.build_id' => 'f06dc9f0',
    'container.build_time' => 1555772975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNZ2URE');
